site_name: Sylvis Custom Item Wiki

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  - md_in_html

plugins:
  - search
  - macros

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Testing:
    - Main Page: testing/main.md
    - Testing Page: testing/testing.md
    - Styleguide: testing/styleguide.md
  - Tobacco:
    - Tobacco Main Page: tobacco/main.md
