site_name: Sylvis Custom Item Wiki
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo

nav:
  - Home: index.md
  - Testing: testing.md
  - Custom Items:
    - Schwerter: items/swords.md
    - Werkzeuge: items/tools.md
