site_name: Sylvis Custom Item Wiki

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  - md_in_html

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Testing: testing.md
  - Custom Items:
    - Schwerter: items/swords.md
    - Werkzeuge: items/tools.md
